### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by rscottjohnson** [gbremble/group3-project1#82]
Following on the project requirement to be 'well documented', update the README to follow the recommended README format from [help.github.com](https://help.github.com/articles/about-readmes/):

> A README is often the first item a visitor will see when visiting your repository. README files typically include information on:
> 
> What the project does
> Why the project is useful
> How users can get started with the project
> Where users can get help with your project
> Who maintains and contributes to the project

**Comment by mickburgess** [comment]
PR has been merged.
